service: getetfprice
provider:
  name: aws
  runtime: nodejs10.x
  region: "eu-central-1"

functions:
  getetfprice:
    handler: handler.getetfprice
    events:
      # - schedule: rate(2 hours)
      # - schedule: cron(0 12 * * ? *)
