service: getetfprice
provider:
  name: aws
  runtime: nodejs10.x
  region: "eu-central-1"

functions:
  getetfprice:
    handler: handler.getetfprice
    events:
      #- schedule: rate(1 minute)
      - schedule: cron(18 30 * * ? *)
